@startuml Заказ состояния

hide empty description
state store {
    state INITIATED
    state FILE_UPLOADED
    state SUBMITTED
}

state MES {
    state PRICE_CALCULATED
}

state CRM {
    state MANUFACTURING_APPROVED
}

[*] --> INITIATED
INITIATED --> FILE_UPLOADED
FILE_UPLOADED --> SUBMITTED
SUBMITTED --> PRICE_CALCULATED
PRICE_CALCULATED --> MANUFACTURING_APPROVED
MANUFACTURING_APPROVED --> MANUFACTURING_STARTED
MANUFACTURING_STARTED --> MANUFACTURING_COMPLETED
MANUFACTURING_COMPLETED --> PACKAGING
PACKAGING --> SHIPPED
SHIPPED --> CLOSED
CLOSED --> [*]
@enduml