@startuml Граф состояний заказа

skinparam linetype ortho

hide empty description
state store {
    state INITIATED
    state FILE_UPLOADED
    state SUBMITTED
}

state MES {
    state PRICE_CALCULATED
    state MANUFACTURING_STARTED
    state MANUFACTURING_COMPLETED
    state PACKAGING
    state SHIPPED
}

state CRM {
    state MANUFACTURING_APPROVED
    state CLOSED
}

[*] --> INITIATED
INITIATED --> FILE_UPLOADED
FILE_UPLOADED --> SUBMITTED
SUBMITTED --> PRICE_CALCULATED
PRICE_CALCULATED --> MANUFACTURING_APPROVED
MANUFACTURING_APPROVED --> MANUFACTURING_STARTED
MANUFACTURING_STARTED --> MANUFACTURING_COMPLETED
MANUFACTURING_COMPLETED --> PACKAGING
PACKAGING --> SHIPPED
SHIPPED --> CLOSED
CLOSED --> [*]
@enduml